name: eco_footprint_tracker
description: "An engaging mobile app that helps users understand and reduce their environmental impact through daily activity tracking, gamification, and community engagement."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  
  # State Management
  provider: ^6.1.2
  
  # Storage & Database
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  path: ^1.9.0
  
  # Networking
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Location & Camera
  geolocator: ^11.0.0
  camera: ^0.10.5+9
  qr_code_scanner: ^1.0.1
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  # Push Notifications
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
  # JSON Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    
  fonts:
    - family: EcoFont
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
