name: eco_footprint_tracker
description: "An engaging mobile app that helps users understand and reduce their environmental impact through daily activity tracking, gamification, and community engagement."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  
  # State Management
  provider: ^6.1.2
  
  # Storage & Database
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  path: ^1.9.0
  
  # Networking
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Location & Camera
  geolocator: ^11.0.0
  camera: ^0.10.5+9
  qr_code_scanner: ^1.0.1
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  # Push Notifications
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
  # JSON Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
